#!/usr/bin/env python2.7
"""
Will read an sql generated by pg_dump and alter all the ids to anonymize these.
!!!!! Student names are NOT anonymized !!!!!
"""
import os
import argparse
import random

parser = argparse.ArgumentParser()
parser.add_argument(
    'infile', metavar='infile', type=str,
    help='The input file sql')
parser.add_argument(
    'outfile', metavar='outfile', type=str,
    help='The output file sql')
args = parser.parse_args()


# First pass collect ids
print("Opening file")
infile = open(args.infile, 'r')
seen_user_start = False
ids = []
for line in infile:

    if seen_user_start:
        if "\\." in line:
            print("Found end")
            break
        columns = line.split("\t")
        if columns[0].isdigit() and len(columns[0]) == 7:
            ids.append(columns[0])
            print(columns[0])
    else:
        if 'COPY "user"' in line:
            print("Found users")
            seen_user_start = True
infile.close()

num_ids = len(ids)

new_ids = random.sample(xrange(1000000, 9999999), num_ids)

id_dict = dict(zip(ids, new_ids))

infile = open(args.infile, 'r')
outfile = open(args.outfile, 'w')

in_users = False
for line in infile:
    if "local_" in line:
        index = line.find("local_")
        id_string = line[index+6:index+13]
        if id_string.isdigit():
            line = line.replace("local_"+id_string, "local_"+str(id_dict[id_string]))
    if seen_user_start:
        if "\\." in line:
            in_users = False
        else:
            columns = line.split("\t")
            if columns[0].isdigit() and len(columns[0]) == 7:
                line = str(id_dict[columns[0]])+line[7:]
    else:
        if 'COPY "user"' in line:
            in_users = True
    outfile.write(line)

infile.close()
outfile.close()
